import json
import shutil
from datetime import datetime, timezone
from pathlib import Path

from app.config import settings
from app.schemas import Case, QICaseReview

PCR_PLACEHOLDER = """# Patient Care Report — placeholder

This PCR is a placeholder generated by the case loader because no `pcr.md`
existed for this case. Replace it with a real PCR for live pipeline runs.

## Incident
- Type: cardiac arrest (witnessed)
- Initial rhythm: unknown
- Bystander CPR: unknown

## Narrative
No narrative provided yet.
"""


def _cases_root() -> Path:
    return settings.CASES_DIR.resolve()


def _fixtures_root() -> Path:
    return settings.FIXTURES_DIR.resolve()


def _case_dir(case_id: str) -> Path:
    return _cases_root() / case_id


def _seed_case_01() -> None:
    """One-time seed: copy the canonical sample QI Case Review into
    cases/case_01/aar.json so GET /api/cases/case_01/aar returns realistic
    data before the pipeline has been run.

    Step 3 of the QI Case Review update will rename the on-disk file
    from aar.json to review.json with a one-time migration; until then
    the filename stays put to keep the existing cache + tests working.
    """
    case_dir = _case_dir("case_01")
    if not case_dir.exists():
        return
    target = case_dir / "aar.json"
    if target.exists():
        return
    fixture = _fixtures_root() / "sample_qi_review.json"
    if fixture.exists():
        shutil.copy(fixture, target)


def _ensure_pcr(case_dir: Path) -> Path:
    pcr = case_dir / "pcr.md"
    if not pcr.exists():
        pcr.write_text(PCR_PLACEHOLDER, encoding="utf-8")
    return pcr


def _build_case(case_dir: Path) -> Case:
    pcr_path = _ensure_pcr(case_dir)
    video_path = case_dir / "video.mp4"
    audio_path = case_dir / "audio.mp3"
    incident_date = datetime.fromtimestamp(case_dir.stat().st_mtime, tz=timezone.utc)
    return Case(
        case_id=case_dir.name,
        incident_type="cardiac_arrest",
        incident_date=incident_date,
        pcr_path=str(pcr_path),
        video_path=str(video_path),
        audio_path=str(audio_path),
        metadata={},
    )


def list_cases() -> list[Case]:
    root = _cases_root()
    if not root.exists():
        return []
    _seed_case_01()
    cases: list[Case] = []
    for entry in sorted(root.iterdir()):
        if not entry.is_dir():
            continue
        cases.append(_build_case(entry))
    return cases


def load_case(case_id: str) -> Case:
    case_dir = _case_dir(case_id)
    if not case_dir.is_dir():
        raise FileNotFoundError(f"Case not found: {case_id}")
    if case_id == "case_01":
        _seed_case_01()
    return _build_case(case_dir)


def load_pcr_content(case_id: str) -> str:
    case_dir = _case_dir(case_id)
    if not case_dir.is_dir():
        raise FileNotFoundError(f"Case not found: {case_id}")
    pcr_path = _ensure_pcr(case_dir)
    return pcr_path.read_text(encoding="utf-8")


def load_cached_aar(case_id: str) -> QICaseReview | None:
    case_dir = _case_dir(case_id)
    if case_id == "case_01":
        _seed_case_01()
    aar_path = case_dir / "aar.json"
    if not aar_path.exists():
        return None
    data = json.loads(aar_path.read_text(encoding="utf-8"))
    return QICaseReview.model_validate(data)


def save_cached_aar(case_id: str, review: QICaseReview) -> Path:
    case_dir = _case_dir(case_id)
    if not case_dir.is_dir():
        raise FileNotFoundError(f"Case not found: {case_id}")
    aar_path = case_dir / "aar.json"
    aar_path.write_text(review.model_dump_json(indent=2), encoding="utf-8")
    return aar_path


def clear_cached_aar(case_id: str) -> bool:
    """Delete cases/{id}/aar.json. Returns True if a file was removed."""
    case_dir = _case_dir(case_id)
    if not case_dir.is_dir():
        raise FileNotFoundError(f"Case not found: {case_id}")
    aar_path = case_dir / "aar.json"
    if not aar_path.exists():
        return False
    aar_path.unlink()
    return True
