import json
import logging
import shutil
from datetime import datetime, timezone
from pathlib import Path

from app.config import settings
from app.schemas import Case, QICaseReview

logger = logging.getLogger(__name__)

PCR_PLACEHOLDER = """# Patient Care Report — placeholder

This PCR is a placeholder generated by the case loader because no `pcr.md`
existed for this case. Replace it with a real PCR for live pipeline runs.

## Incident
- Type: cardiac arrest (witnessed)
- Initial rhythm: unknown
- Bystander CPR: unknown

## Narrative
No narrative provided yet.
"""


def _cases_root() -> Path:
    return settings.CASES_DIR.resolve()


def _fixtures_root() -> Path:
    return settings.FIXTURES_DIR.resolve()


def _case_dir(case_id: str) -> Path:
    return _cases_root() / case_id


def _review_path(case_dir: Path) -> Path:
    return case_dir / "review.json"


def migrate_legacy_aar_caches() -> int:
    """Migrate pre-existing cases/*/aar.json files to review.json.

    Step 3 of the QI Case Review update renames the on-disk cache file.
    On startup, walk the cases dir once and:

    - If review.json already exists for the case, leave aar.json alone
      and log a warning (newer data wins).
    - If aar.json parses as a valid QICaseReview, rename it.
    - Otherwise the file is from before Step 1's schema change and is
      no longer compatible; delete it. case_01 will be re-seeded from
      the canonical fixture on next read; other cases simply lose the
      stale cache until the pipeline runs again.

    Returns the number of files renamed (does not include deletions).
    """

    root = _cases_root()
    if not root.exists():
        return 0
    migrated = 0
    for case_dir in sorted(root.iterdir()):
        if not case_dir.is_dir():
            continue
        legacy = case_dir / "aar.json"
        if not legacy.exists():
            continue
        target = _review_path(case_dir)
        if target.exists():
            logger.warning(
                "Skipping migration for %s — review.json already present alongside legacy aar.json.",
                case_dir.name,
            )
            continue
        try:
            data = json.loads(legacy.read_text(encoding="utf-8"))
            QICaseReview.model_validate(data)
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "Discarding legacy %s/aar.json (incompatible with QICaseReview schema: %s).",
                case_dir.name,
                exc.__class__.__name__,
            )
            legacy.unlink()
            continue
        legacy.rename(target)
        migrated += 1
        logger.info("Migrated %s/aar.json → review.json", case_dir.name)
    return migrated


def _seed_case_01() -> None:
    """One-time seed: copy the canonical sample QI Case Review into
    cases/case_01/review.json so GET /api/cases/case_01/review returns
    realistic data before the pipeline has been run.
    """
    case_dir = _case_dir("case_01")
    if not case_dir.exists():
        return
    target = _review_path(case_dir)
    if target.exists():
        return
    fixture = _fixtures_root() / "sample_qi_review.json"
    if fixture.exists():
        shutil.copy(fixture, target)


def _ensure_pcr(case_dir: Path) -> Path:
    pcr = case_dir / "pcr.md"
    if not pcr.exists():
        pcr.write_text(PCR_PLACEHOLDER, encoding="utf-8")
    return pcr


def _build_case(case_dir: Path) -> Case:
    pcr_path = _ensure_pcr(case_dir)
    video_path = case_dir / "video.mp4"
    audio_path = case_dir / "audio.mp3"
    incident_date = datetime.fromtimestamp(case_dir.stat().st_mtime, tz=timezone.utc)
    metadata: dict = {}
    metadata_path = case_dir / "metadata.json"
    if metadata_path.exists():
        try:
            metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            logger.warning("Ignoring unparseable %s/metadata.json", case_dir.name)
    return Case(
        case_id=case_dir.name,
        incident_type="cardiac_arrest",
        incident_date=incident_date,
        pcr_path=str(pcr_path),
        video_path=str(video_path),
        audio_path=str(audio_path),
        cad_path=str(case_dir / "cad.json") if (case_dir / "cad.json").exists() else None,
        metadata=metadata,
    )


def next_case_id() -> str:
    """Return the next sequential case_NN id by scanning CASES_DIR.

    Pads to at least 2 digits to match the existing repo convention
    (case_01, case_02, ...). Cases with non-numeric or non-case_ prefixes
    are ignored.
    """
    root = _cases_root()
    max_n = 0
    if root.exists():
        for entry in root.iterdir():
            if not entry.is_dir():
                continue
            name = entry.name
            if not name.startswith("case_"):
                continue
            suffix = name[len("case_") :]
            if not suffix.isdigit():
                continue
            max_n = max(max_n, int(suffix))
    return f"case_{max_n + 1:02d}"


def list_cases() -> list[Case]:
    root = _cases_root()
    if not root.exists():
        return []
    _seed_case_01()
    cases: list[Case] = []
    for entry in sorted(root.iterdir()):
        if not entry.is_dir():
            continue
        cases.append(_build_case(entry))
    return cases


def load_case(case_id: str) -> Case:
    case_dir = _case_dir(case_id)
    if not case_dir.is_dir():
        raise FileNotFoundError(f"Case not found: {case_id}")
    if case_id == "case_01":
        _seed_case_01()
    return _build_case(case_dir)


def load_pcr_content(case_id: str) -> str:
    case_dir = _case_dir(case_id)
    if not case_dir.is_dir():
        raise FileNotFoundError(f"Case not found: {case_id}")
    pcr_path = _ensure_pcr(case_dir)
    return pcr_path.read_text(encoding="utf-8")


def load_cached_review(case_id: str) -> QICaseReview | None:
    case_dir = _case_dir(case_id)
    if case_id == "case_01":
        _seed_case_01()
    review_path = _review_path(case_dir)
    if not review_path.exists():
        return None
    data = json.loads(review_path.read_text(encoding="utf-8"))
    return QICaseReview.model_validate(data)


def save_cached_review(case_id: str, review: QICaseReview) -> Path:
    case_dir = _case_dir(case_id)
    if not case_dir.is_dir():
        raise FileNotFoundError(f"Case not found: {case_id}")
    review_path = _review_path(case_dir)
    review_path.write_text(review.model_dump_json(indent=2), encoding="utf-8")
    return review_path


def clear_cached_review(case_id: str) -> bool:
    """Delete cases/{id}/review.json. Returns True if a file was removed."""
    case_dir = _case_dir(case_id)
    if not case_dir.is_dir():
        raise FileNotFoundError(f"Case not found: {case_id}")
    review_path = _review_path(case_dir)
    if not review_path.exists():
        return False
    review_path.unlink()
    return True
